import { ChildProps } from '@/types';
import type { Metadata } from 'next';
import '../globals.css';
import { Navbar } from './components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: ChildProps) {
  return (
    <div className='h-full'>
      <Navbar />
      <main className='h-full pt-40'>{children}</main>
    </div>
  );
}
